version: '3.8'

services:
  # Simple attendance application
  simple-attendance:
    build:
      context: .
      dockerfile: apps/simple-attendance/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    restart: unless-stopped

networks:
  default:
    driver: bridge
